# ----------------------------------------------------------------------
# D4 symmetry diagnostics on the Yelmo C-grid.
#
# Scalars live on cell centres (aa). Velocity components live on cell faces:
# ux(i, j) on the right face of cell i (acx), uy(i, j) on the top face of
# cell j (acy). Under the reflection x → −x (see tests/README_symcheck.md):
#   aa:  f(i, j)  → f(nx+1−i, j)
#   acx: ux(i, j) → −ux(nx−i, j)   (i = nx maps to the border, skipped)
#   acy: uy(i, j) →  uy(nx+1−i, j)
# The transposition x ↔ y swaps the components: ux(i, j) ↔ uy(j, i).
# The group D4 is generated by the two reflections and the transposition.
# ----------------------------------------------------------------------

export d4_errors, symmetry_report, symmetry_series

# The seven non-identity elements of D4 as compositions of
# mx (x → −x), my (y → −y) and tr (x ↔ y), applied right to left.
const D4_OPS = (("mx",), ("my",), ("mx", "my"), ("tr",),
                ("tr", "mx"), ("tr", "my"), ("tr", "mx", "my"))

d4_name(op) = join(op, "∘")

"Apply one generator to a scalar aa field (2D, or 3D with the vertical as third dimension)."
function apply_aa(f::AbstractArray, g::String)
    g == "mx" && return reverse(f; dims = 1)
    g == "my" && return reverse(f; dims = 2)
    g == "tr" && return permutedims(f, (2, 1, (3:ndims(f))...))
    error("unknown generator $g")
end

"""
Apply one generator to a staggered velocity pair (ux on acx, uy on acy).
Faces on the upper border have no mirror image and are set to NaN.
"""
function apply_vel(ux::AbstractMatrix, uy::AbstractMatrix, g::String)
    nx, ny = size(ux)
    if g == "mx"
        ux2 = fill(NaN, nx, ny)
        ux2[1:nx-1, :] .= -ux[nx-1:-1:1, :]
        return ux2, uy[end:-1:1, :]
    elseif g == "my"
        uy2 = fill(NaN, nx, ny)
        uy2[:, 1:ny-1] .= -uy[:, ny-1:-1:1]
        return ux[:, end:-1:1], uy2
    elseif g == "tr"
        return permutedims(uy), permutedims(ux)
    end
    error("unknown generator $g")
end

function apply_op_aa(f, op)
    for g in reverse(op)
        f = apply_aa(f, g)
    end
    return f
end

function apply_op_vel(ux, uy, op)
    for g in reverse(op)
        ux, uy = apply_vel(ux, uy, g)
    end
    return ux, uy
end

"""
Maximum of |a − b| over the points where both are finite, relative to max |a|
(`range = false`) or to max a − min a (`range = true`, for fields with an
offset such as the enthalpy).
"""
function relerr(a, b; range::Bool = false)
    m = isfinite.(a) .& isfinite.(b)
    any(m) || return 0.0
    scale = range ? maximum(a[m]) - minimum(a[m]) : maximum(abs, a[m])
    scale == 0 && return 0.0
    return maximum(abs, (a .- b)[m]) / scale
end

"""
    d4_errors(f; range = false) -> Dict{String,Float64}
    d4_errors(ux, uy) -> Dict{String,Float64}

Relative symmetry error of a scalar aa field (2D, or 3D with the vertical as
third dimension), or of a staggered velocity pair, for each non-identity
element of D4. `range` selects the normalization of `relerr`.
"""
d4_errors(f::AbstractArray; range::Bool = false) =
    Dict(d4_name(op) => relerr(f, apply_op_aa(f, op); range) for op in D4_OPS)

function d4_errors(ux::AbstractMatrix, uy::AbstractMatrix)
    out = Dict{String,Float64}()
    for op in D4_OPS
        ux2, uy2 = apply_op_vel(ux, uy, op)
        out[d4_name(op)] = max(relerr(ux, ux2), relerr(uy, uy2))
    end
    return out
end

"Read a 2D field at time index `k` (default: last), with missing values set to 0."
function read2d(ds, name; k = nothing)
    v = ds[name]
    nd = ndims(v)
    data = nd == 2 ? v[:, :] : (k === nothing ? v[:, :, end] : v[:, :, k])
    return Float64.(coalesce.(data, 0.0))
end

"""
    symmetry_report(file; k = nothing, io = stdout) -> Dict{String,Float64}

Maximum D4 symmetry error over all group elements for the standard fields of a
Yelmo output file (yelmo.nc), at time index `k` (default: last). Fields that
are not in the file are skipped. Returns field => maximum error.
"""
function symmetry_report(file::AbstractString; k = nothing, io = stdout)
    out = Dict{String,Float64}()
    NCDataset(file) do ds
        size(ds["xc"], 1) == size(ds["yc"], 1) ||
            error("symmetry_report: the grid must be square (nx = ny).")
        for name in ("H_ice", "z_srf", "f_grnd", "uxy_bar", "uxy_s", "T_prime_b", "Q_strn_b")
            haskey(ds, name) || continue
            out[name] = maximum(values(d4_errors(read2d(ds, name; k))))
        end
        for (nx_, ny_) in (("ux_bar", "uy_bar"), ("ux_s", "uy_s"), ("ux_b", "uy_b"))
            (haskey(ds, nx_) && haskey(ds, ny_)) || continue
            out[nx_ * "," * ny_] = maximum(values(d4_errors(read2d(ds, nx_; k), read2d(ds, ny_; k))))
        end
    end
    for name in sort(collect(keys(out)))
        println(io, rpad(name, 16), "  max D4 error = ", round(out[name]; sigdigits = 3))
    end
    return out
end

"""
    symmetry_series(run) -> NamedTuple

Time series of the maximum D4 symmetry error over all group elements, from the
2D output (`run`/yelmo.nc) and, when present, the 3D output (`run`/yelmo3D.nc).
Fields: H_ice, the depth-averaged velocity (ux_bar, uy_bar) and the enthalpy on
all layers (relative to its range, since it has an offset). Returns
(time, H_ice, vel, enth), with `enth` empty without a 3D file.
"""
function symmetry_series(run::AbstractString)
    file2D = joinpath(run, "yelmo.nc")
    file3D = joinpath(run, "yelmo3D.nc")
    time, eH, eu = NCDataset(file2D) do ds
        size(ds["xc"], 1) == size(ds["yc"], 1) ||
            error("symmetry_series: the grid must be square (nx = ny).")
        nt = length(ds["time"])
        eH = [maximum(values(d4_errors(read2d(ds, "H_ice"; k)))) for k in 1:nt]
        eu = [maximum(values(d4_errors(read2d(ds, "ux_bar"; k), read2d(ds, "uy_bar"; k)))) for k in 1:nt]
        Float64.(ds["time"][:]), eH, eu
    end
    ee = Float64[]
    if isfile(file3D)
        ee = NCDataset(file3D) do ds
            v = ds["enth"]
            [maximum(values(d4_errors(Float64.(coalesce.(v[:, :, :, k], 0.0)); range = true)))
             for k in 1:length(ds["time"])]
        end
        length(ee) == length(time) || error("symmetry_series: yelmo.nc and yelmo3D.nc have different times.")
    end
    return (time = time, H_ice = eH, vel = eu, enth = ee)
end
